// Default currency data used for seeding the database from the admin panel
export const DEFAULT_CURRENCIES = [
    { code: 'USD', name: 'US Dollar', symbol: '$', icon: '🇺🇸' },
    { code: 'EUR', name: 'Euro', symbol: '€', icon: '🇪🇺' },
    { code: 'GBP', name: 'British Pound', symbol: '£', icon: '🇬🇧' },
    { code: 'JPY', name: 'Japanese Yen', symbol: '¥', icon: '🇯🇵' },
    { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', icon: '🇨🇳' },
    { code: 'KRW', name: 'South Korean Won', symbol: '₩', icon: '🇰🇷' },
    { code: 'INR', name: 'Indian Rupee', symbol: '₹', icon: '🇮🇳' },
    { code: 'RUB', name: 'Russian Ruble', symbol: '₽', icon: '🇷🇺' },
    { code: 'TRY', name: 'Turkish Lira', symbol: '₺', icon: '🇹🇷' },
    { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', icon: '🇧🇷' },
    { code: 'MXN', name: 'Mexican Peso', symbol: '$', icon: '🇲🇽' },
    { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', icon: '🇦🇺' },
    { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', icon: '🇨🇦' },
    { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', icon: '🇨🇭' },
    { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', icon: '🇸🇪' },
    { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', icon: '🇳🇴' },
    { code: 'DKK', name: 'Danish Krone', symbol: 'kr', icon: '🇩🇰' },
    { code: 'PLN', name: 'Polish Złoty', symbol: 'zł', icon: '🇵🇱' },
    { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', icon: '🇦🇿' },
    { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', icon: '🇦🇪' },
    { code: 'SAR', name: 'Saudi Riyal', symbol: '﷼', icon: '🇸🇦' },
    { code: 'ILS', name: 'Israeli Shekel', symbol: '₪', icon: '🇮🇱' },
    { code: 'THB', name: 'Thai Baht', symbol: '฿', icon: '🇹🇭' },
    { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', icon: '🇸🇬' },
    { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', icon: '🇭🇰' },
    { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', icon: '🇳🇿' },
    { code: 'ZAR', name: 'South African Rand', symbol: 'R', icon: '🇿🇦' },
    { code: 'PHP', name: 'Philippine Peso', symbol: '₱', icon: '🇵🇭' },
    { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', icon: '🇮🇩' },
    { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', icon: '🇲🇾' },
    { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', icon: '🇻🇳' },
    { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', icon: '🇵🇰' },
    { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', icon: '🇧🇩' },
    { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', icon: '🇳🇬' },
    { code: 'EGP', name: 'Egyptian Pound', symbol: 'E£', icon: '🇪🇬' },
    { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', icon: '🇰🇿' },
    { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', icon: '🇺🇦' },
    { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', icon: '🇨🇿' },
    { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', icon: '🇭🇺' },
    { code: 'RON', name: 'Romanian Leu', symbol: 'lei', icon: '🇷🇴' },
];
